version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes: 
      - ./examples/tmp/test-restored.sql:/docker-entrypoint-initdb.d/import.sql
      - ./examples/postgres/init.sh:/docker-entrypoint-initdb.d/init.sh

  adminer:
    image: adminer
    restart: always
    ports:
      - 8090:8080
