version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    volumes: 
      - ./examples/tmp/test-restored.sql:/docker-entrypoint-initdb.d/import.sql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
